### ISSUE TITLE
ZeroDivisionError: float division by zero : geneBody_coverage.py

### ISSUE THREAD

**Issue by sb43** [MonashBioinformaticsPlatform/RSeQC#1]
Hi,
I am getting following error in geneBody_coverage.py script.
geneBody_coverage.py -i 232384.bam -r HouseKeepingGenes.bed -f png -o 232384 lib/python2.7/site-packages/RSeQC-2.6.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/geneBody_coverage.py:82: RuntimeWarning: invalid value encountered in double_scalars
  tmp.append(((i - mid_value)/sigma)**3)
Traceback (most recent call last):
  File "bin/geneBody_coverage.py", line 5, in <module>
    pkg_resources.run_script('RSeQC==2.6.3', 'geneBody_coverage.py')
  File "lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "lib/python2.7/site-packages/RSeQC-2.6.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/geneBody_coverage.py", line 302, in <module>
    main()
  File "lib/python2.7/site-packages/RSeQC-2.6.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/geneBody_coverage.py", line 284, in main
    dataset.append((name, [(i -min(dat))/(max(dat) - min(dat)) for i in dat], skewness))
ZeroDivisionError: float division by zero

Thanks,
Shriram

**Comment by serine** [comment]
Hi Shriram,

This a fork of original `RSeQC`. It is hard to see that, since original code is at sourceforge, here is the link http://rseqc.sourceforge.net/ . I simple got latest tarball at the time and commited it all in one chunk here. I then branched off to do my own stuff. If you are interested have a look at **fresh** branch. I was only really interested in `read_dist.py` module, which I re-wrote, but haven't really used it. I moved on to `QualiMap` tool instead, that gives me exonic/intronic rates. 

I can't really help you with your problem, but it looks like you've managed to sort it out given the pull requiest.
