### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by drumair** [MonashBioinformaticsPlatform/RSeQC#11]
Hi,
I am getting the following error when I try to run the command

rseqc read_dist --input_file /abc_starAligned.sortedByCoord.out.bam --gene_models /gencode.v43.annotation.gtf

Traceback (most recent call last):
  File "/usr/local/bin/rseqc", line 4, in <module>
    __import__('pkg_resources').run_script('RSeQC==2.6.4', 'rseqc')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/RSeQC-2.6.4-py3.8.egg/EGG-INFO/scripts/rseqc", line 8, in <module>
    from rseqc.modules import read_dist
  File "/usr/local/lib/python3.8/dist-packages/RSeQC-2.6.4-py3.8.egg/rseqc/modules/read_dist.py", line 192
    (cds_exon_r,
               ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by drumair** [comment]
She same is for 
rseqc --help
Traceback (most recent call last):
  File "/usr/local/bin/rseqc", line 4, in <module>
    __import__('pkg_resources').run_script('RSeQC==2.6.4', 'rseqc')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/RSeQC-2.6.4-py3.8.egg/EGG-INFO/scripts/rseqc", line 8, in <module>
    from rseqc.modules import read_dist
  File "/usr/local/lib/python3.8/dist-packages/RSeQC-2.6.4-py3.8.egg/rseqc/modules/read_dist.py", line 192
    (cds_exon_r,
               ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by laetitiarialland** [comment]
Hello @drumair , 
I have the same error.. Do you find any solution ? 
Thank you for your help !! 

Kinds regards, 
Laëtitia
